name: Deploy Django to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Initial deploy to EC2
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          sudo apt update
          sudo apt install git python3-pip python3-venv nginx -y

          cd /home/${USER}
          if [ ! -d "myproject" ]; then
            git clone https://github.com/RuslanRRT/final.git
          fi
          
          cd myproject
          python3 -m venv venv
          source venv/bin/activate
          pip install django
          python3 manage.py migrate
          python3 manage.py collectstatic --noinput
          
          sudo systemctl restart gunicorn || echo "Gunicorn not set up yet"
          sudo systemctl restart nginx || echo "Nginx restarted"
        EOF
